version: '3.6'

services:
  peatio:
    restart: always
    image: "quay.io/openware/peatio:3.1.0-e2122b0"
    environment:
      - VAULT_TOKEN=s.jynUecCN4hg1ShocjVXYGAFj
    env_file:
      - ../config/kaigara.env
      - ../config/peatio.env
    volumes:
      - ../config/peatio/seed:/opt/peatio/config/seed
      - ../config/peatio/management_api_v1.yml:/opt/peatio/config/management_api.yml
      - ../config/peatio/plugins.yml:/opt/peatio/config/plugins.yml
      - ../config/peatio/abilities.yml:/opt/peatio/config/abilities.yml
    labels: {}
    command: bash -c "bin/link_config && kaigara bundle exec puma --config config/puma.rb"

  barong:
    restart: always
    image: "quay.io/openware/barong:3.1.0-8c60713"
    environment:
      - BARONG_VAULT_TOKEN=s.pMddsCmMP7qum9rammcCUB9O
    env_file:
      - ../config/kaigara.env
      - ../config/barong.env
    volumes:
      - ../config/secrets:/secrets:ro
      - ../config/barong/seeds.yml:/home/app/config/seeds.yml
      - ../config/barong/barong.yml:/home/app/config/barong.yml
      - ../config/barong/authz_rules.yml:/home/app/config/authz_rules.yml
      - ../config/barong/management_api.yml:/home/app/config/management_api.yml
      - ../config/barong/abilities.yml:/home/app/config/abilities.yml
    command: bash -c "kaigara bundle exec puma --config config/puma.rb"

  applogic:
    restart: always
    image: "rubykube/applogic:latest"
    env_file:
      - ../config/applogic.env
      - ../config/kaigara.env
    volumes:
      - ../config/applogic/management_api_v2.yml:/home/app/config/management_api_v2.yml

  sonic:
    restart: always
    image: "jmartin20k/fortem1.com.br-tokenizadora:v5.0.0.304"
    environment:
      - VAULT_TOKEN=s.hi9UK3MOAQkc96vo3WWpEYRi
    env_file:
      - ../config/sonic.env
      - ../config/kaigara.env
    entrypoint: /bin/sh -c "kaigara ./bin/sonic serve"
    labels:
      - "traefik.http.routers.sonic-fortem.rule=Host(`www.fortem1.com.br`) && PathPrefix(`/sonic`)"
      - "traefik.enable=true"
      - "traefik.http.services.sonic-fortem.loadbalancer.server.port=6969"
      - "traefik.http.routers.sonic-fortem.entrypoints=web"

  tower:
    restart: always
    image: "quay.io/openware/tower:3.1.0-1f64f44"
    labels:
      - "traefik.http.routers.tower-fortem.rule=Host(`www.fortem1.com.br`) && PathPrefix(`/tower`)"
      - "traefik.enable=true"
      - "traefik.http.services.tower-fortem.loadbalancer.server.port=8080"
      - "traefik.http.routers.tower-fortem.entrypoints=web"

  frontend:
    restart: always
    image: "jmartin20k/fortem1.com.br-tokenizadora:v5.0.0.335"
    volumes:
      - ../config/frontend/env.js:/usr/share/nginx/html/config/env.js
    labels:
      - "traefik.http.routers.frontend-fortem.rule=Host(`www.fortem1.com.br`>) && PathPrefix(`/`)"
      - "traefik.enable=true"
      - "traefik.http.services.frontend-fortem.loadbalancer.server.port=3000"
      - "traefik.http.routers.frontend-fortem.entrypoints=web"
