# pass for whitelisted (public) routes
# block for blacklisted routes
#
rules:
  pass:
    - api/v2/barong/identity
    - api/v2/barong/public
    - api/v2/auth/identity
    - api/v2/auth/public
    - api/v2/peatio/public
    - api/v2/trade/public
    - api/v2/websocket/public
    - api/v2/ranger/public
    - api/v2/applogic/public
    - api/public
    - api/ieo
  block:

